name: Build

on: [push, pull_request]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up JDK
              uses: actions/setup-java@v1
              with:
                java-version: '11'
                java-package: 'jdk+fx'

            - name: Setup Maven
              env:
                TOKEN: ${{ secrets.GITHUBTOKEN }}
                USERNAME: JeffreyRiggle
              run: |
                envsubst < settings.tmpl > ~/.m2/settings.xml

            - name: Build with Maven
              working-directory: examples/sharedui
              run: xvfb-run mvn install

            - name: Publish
              working-directory: examples/sharedui
              run: xvfb-run mvn deploy -Drevision="${GITHUB_RUN_NUMBER}"

            - name: Build Complex Shell
              working-directory: examples/complexshell
              run: xvfb-run mvn install -Drevision="${GITHUB_RUN_NUMBER}"

            - name: Build Custom Splash Screen Shell
              working-directory: examples/customsplashscreenshell
              run: xvfb-run mvn install -Drevision="${GITHUB_RUN_NUMBER}"

            - name: Build MDI Shell
              working-directory: examples/multipledocumentshell
              run: xvfb-run mvn install -Drevision="${GITHUB_RUN_NUMBER}"

            - name: Build SDI Shell
              working-directory: examples/singledocumentshell
              run: xvfb-run mvn install -Drevision="${GITHUB_RUN_NUMBER}"

            - name: Build Theme Shell
              working-directory: examples/themeshell
              run: xvfb-run mvn install -Drevision="${GITHUB_RUN_NUMBER}"